# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"y\n\nSensorData\x12\x15\n\x03imu\x18\x01 \x01(\x0b\x32\x08.IMUData\x12\x1a\n\x03\x61tt\x18\x02 \x01(\x0b\x32\r.AttitudeData\x12\x1b\n\x04odom\x18\x03 \x01(\x0b\x32\r.OdometryData\x12\x1b\n\x06\x61nalog\x18\x04 \x01(\x0b\x32\x0b.AnalogData\"\x19\n\nGetRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"8\n\x07IMUData\x12\x16\n\x04gyro\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x15\n\x03\x61\x63\x63\x18\x02 \x01(\x0b\x32\x08.Vector3\"%\n\x0c\x41ttitudeData\x12\x15\n\x03\x61ng\x18\x01 \x01(\x0b\x32\x08.Vector3\"I\n\x0cOdometryData\x12\x15\n\x03pos\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x15\n\x03vel\x18\x02 \x01(\x0b\x32\x08.Vector3\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"\x1d\n\nAnalogData\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32?\n\rDriverManager\x12.\n\x10GetSensorDataRPC\x12\x0b.GetRequest\x1a\x0b.SensorData0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=13
  _globals['_SENSORDATA']._serialized_end=134
  _globals['_GETREQUEST']._serialized_start=136
  _globals['_GETREQUEST']._serialized_end=161
  _globals['_IMUDATA']._serialized_start=163
  _globals['_IMUDATA']._serialized_end=219
  _globals['_ATTITUDEDATA']._serialized_start=221
  _globals['_ATTITUDEDATA']._serialized_end=258
  _globals['_ODOMETRYDATA']._serialized_start=260
  _globals['_ODOMETRYDATA']._serialized_end=333
  _globals['_ANALOGDATA']._serialized_start=335
  _globals['_ANALOGDATA']._serialized_end=364
  _globals['_VECTOR3']._serialized_start=366
  _globals['_VECTOR3']._serialized_end=408
  _globals['_DRIVERMANAGER']._serialized_start=410
  _globals['_DRIVERMANAGER']._serialized_end=473
# @@protoc_insertion_point(module_scope)
