# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navigation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import driver_pb2 as driver__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10navigation.proto\x1a\x0c\x64river.proto\"9\n\x0fVelocityRequest\x12\x12\n\nvelocity_x\x18\x01 \x01(\x02\x12\x12\n\nvelocity_y\x18\x02 \x01(\x02\"J\n\x10VelocityResponse\x12\x1a\n\x12\x63urrent_velocity_x\x18\x01 \x01(\x02\x12\x1a\n\x12\x63urrent_velocity_y\x18\x02 \x01(\x02\"[\n\x0fPositionRequest\x12\x10\n\x08target_x\x18\x01 \x01(\x02\x12\x10\n\x08target_y\x18\x02 \x01(\x02\x12\x10\n\x08target_z\x18\x03 \x01(\x02\x12\x12\n\ntarget_yaw\x18\x04 \x01(\x02\"`\n\x10PositionResponse\x12\x11\n\tcurrent_x\x18\x01 \x01(\x02\x12\x11\n\tcurrent_y\x18\x02 \x01(\x02\x12\x11\n\tcurrent_z\x18\x03 \x01(\x02\x12\x13\n\x0b\x63urrent_yaw\x18\x04 \x01(\x02\"*\n\x0f\x41ltitudeRequest\x12\x17\n\x0ftarget_altitude\x18\x01 \x01(\x02\",\n\x10\x41ltitudeResponse\x12\x18\n\x10\x63urrent_altitude\x18\x01 \x01(\x02\")\n\x0eTakeoffRequest\x12\x17\n\x0ftarget_altitude\x18\x01 \x01(\x02\">\n\x0fTakeoffResponse\x12\x11\n\tis_flying\x18\x01 \x01(\x08\x12\x18\n\x10\x63urrent_altitude\x18\x02 \x01(\x02\"\r\n\x0bLandRequest\";\n\x0cLandResponse\x12\x11\n\tis_landed\x18\x01 \x01(\x08\x12\x18\n\x10\x63urrent_altitude\x18\x02 \x01(\x02\x32\xa2\x02\n\x11NavigationService\x12\x36\n\x0bSetVelocity\x12\x10.VelocityRequest\x1a\x11.VelocityResponse\"\x00\x30\x01\x12<\n\x11SetTargetPosition\x12\x10.PositionRequest\x1a\x11.PositionResponse\"\x00\x30\x01\x12<\n\x11SetTargetAltitude\x12\x10.AltitudeRequest\x1a\x11.AltitudeResponse\"\x00\x30\x01\x12\x30\n\x07Takeoff\x12\x0f.TakeoffRequest\x1a\x10.TakeoffResponse\"\x00\x30\x01\x12\'\n\x04Land\x12\x0c.LandRequest\x1a\r.LandResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VELOCITYREQUEST']._serialized_start=34
  _globals['_VELOCITYREQUEST']._serialized_end=91
  _globals['_VELOCITYRESPONSE']._serialized_start=93
  _globals['_VELOCITYRESPONSE']._serialized_end=167
  _globals['_POSITIONREQUEST']._serialized_start=169
  _globals['_POSITIONREQUEST']._serialized_end=260
  _globals['_POSITIONRESPONSE']._serialized_start=262
  _globals['_POSITIONRESPONSE']._serialized_end=358
  _globals['_ALTITUDEREQUEST']._serialized_start=360
  _globals['_ALTITUDEREQUEST']._serialized_end=402
  _globals['_ALTITUDERESPONSE']._serialized_start=404
  _globals['_ALTITUDERESPONSE']._serialized_end=448
  _globals['_TAKEOFFREQUEST']._serialized_start=450
  _globals['_TAKEOFFREQUEST']._serialized_end=491
  _globals['_TAKEOFFRESPONSE']._serialized_start=493
  _globals['_TAKEOFFRESPONSE']._serialized_end=555
  _globals['_LANDREQUEST']._serialized_start=557
  _globals['_LANDREQUEST']._serialized_end=570
  _globals['_LANDRESPONSE']._serialized_start=572
  _globals['_LANDRESPONSE']._serialized_end=631
  _globals['_NAVIGATIONSERVICE']._serialized_start=634
  _globals['_NAVIGATIONSERVICE']._serialized_end=924
# @@protoc_insertion_point(module_scope)
