site_name: Документация на дроны
nav:
    - Главная: index.md
    - Руководство пользователя:
        - ARA EDU:
            - Обзор: user-guide/ara-edu/overview.md
            - Настройка: user-guide/ara-edu/setup.md
            - Обновление: user-guide/ara-edu/updates.md
        - ARA MINI:
            - Обзор: user-guide/ara-mini/overview.md
            - Настройка: user-guide/ara-mini/setup.md
            - Обновление: user-guide/ara-mini/updates.md
        - ARA FPV:
            - Обзор: user-guide/ara-fpv/overview.md
            - Настройка: user-guide/ara-fpv/setup.md
            - Обновление: user-guide/ara-fpv/updates.md
        - Пульт управления FS-i6x:
            - Обзор: user-guide/fs-i6x/overview.md
            - Подключение: user-guide/fs-i6x/connection.md
            - Назначение каналов: user-guide/fs-i6x/channel-mapping.md
            - Основы управления: user-guide/fs-i6x/basic-operation.md
    - Программирование: programming/first.md
    - Теория:
        - Базовый уровень: theory/basic/test.md
        - Средний уровень: theory/intermediate/test.md
        - Продвинутый уровень: theory/advanced/test.md
    - Лабораторные работы: lab-examples/first.md