# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stream_pb2 as stream__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRawImage = channel.unary_unary(
                '/StreamService/GetRawImage',
                request_serializer=stream__pb2.ImageRequest.SerializeToString,
                response_deserializer=stream__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetProcessedImage = channel.unary_unary(
                '/StreamService/GetProcessedImage',
                request_serializer=stream__pb2.ImageRequest.SerializeToString,
                response_deserializer=stream__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.StartImageStream = channel.unary_unary(
                '/StreamService/StartImageStream',
                request_serializer=stream__pb2.StreamRequest.SerializeToString,
                response_deserializer=stream__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.StopImageStream = channel.unary_unary(
                '/StreamService/StopImageStream',
                request_serializer=stream__pb2.StreamRequest.SerializeToString,
                response_deserializer=stream__pb2.StreamResponse.FromString,
                _registered_method=True)


class StreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRawImage(self, request, context):
        """Получение необработанного изображения
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessedImage(self, request, context):
        """Получение изображения, обработанного OpenCV
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartImageStream(self, request, context):
        """Запуск получения потока изображений
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopImageStream(self, request, context):
        """Остановка получения потока изображений
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRawImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRawImage,
                    request_deserializer=stream__pb2.ImageRequest.FromString,
                    response_serializer=stream__pb2.ImageResponse.SerializeToString,
            ),
            'GetProcessedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessedImage,
                    request_deserializer=stream__pb2.ImageRequest.FromString,
                    response_serializer=stream__pb2.ImageResponse.SerializeToString,
            ),
            'StartImageStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartImageStream,
                    request_deserializer=stream__pb2.StreamRequest.FromString,
                    response_serializer=stream__pb2.StreamResponse.SerializeToString,
            ),
            'StopImageStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopImageStream,
                    request_deserializer=stream__pb2.StreamRequest.FromString,
                    response_serializer=stream__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRawImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamService/GetRawImage',
            stream__pb2.ImageRequest.SerializeToString,
            stream__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamService/GetProcessedImage',
            stream__pb2.ImageRequest.SerializeToString,
            stream__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartImageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamService/StartImageStream',
            stream__pb2.StreamRequest.SerializeToString,
            stream__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopImageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamService/StopImageStream',
            stream__pb2.StreamRequest.SerializeToString,
            stream__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
