# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\"\'\n\x11SensorDataRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\"J\n\x12SensorDataResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\x12 \n\x0bsensor_data\x18\x02 \x01(\x0b\x32\x0b.SensorData\"\x89\x01\n\nSensorData\x12\x1b\n\x06\x61nalog\x18\x01 \x01(\x0b\x32\x0b.AnalogData\x12\x1b\n\x05\x66lags\x18\x02 \x01(\x0b\x32\x0c.SensorFlags\x12\x18\n\x05rc_in\x18\x03 \x01(\x0b\x32\t.RCInData\x12\'\n\x0fsensor_readings\x18\x04 \x03(\x0b\x32\x0e.SensorReading\">\n\nAnalogData\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x01 \x01(\x02\x12\x17\n\x0f\x62\x61ttery_current\x18\x02 \x01(\x02\"B\n\x0bSensorFlags\x12\r\n\x05\x61rmed\x18\x01 \x01(\x08\x12\x13\n\x0blow_battery\x18\x02 \x01(\x08\x12\x0f\n\x07gps_fix\x18\x03 \x01(\x08\"\x1c\n\x08RCInData\x12\x10\n\x08\x63hannels\x18\x01 \x03(\x02\",\n\rSensorReading\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"$\n\x10RCOutDataRequest\x12\x10\n\x08\x63hannels\x18\x01 \x03(\x02\"5\n\x11RCOutDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x86\x01\n\rDriverService\x12<\n\rGetSensorData\x12\x12.SensorDataRequest\x1a\x13.SensorDataResponse\"\x00\x30\x01\x12\x37\n\nSendRCData\x12\x11.RCOutDataRequest\x1a\x12.RCOutDataResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATAREQUEST']._serialized_start=16
  _globals['_SENSORDATAREQUEST']._serialized_end=55
  _globals['_SENSORDATARESPONSE']._serialized_start=57
  _globals['_SENSORDATARESPONSE']._serialized_end=131
  _globals['_SENSORDATA']._serialized_start=134
  _globals['_SENSORDATA']._serialized_end=271
  _globals['_ANALOGDATA']._serialized_start=273
  _globals['_ANALOGDATA']._serialized_end=335
  _globals['_SENSORFLAGS']._serialized_start=337
  _globals['_SENSORFLAGS']._serialized_end=403
  _globals['_RCINDATA']._serialized_start=405
  _globals['_RCINDATA']._serialized_end=433
  _globals['_SENSORREADING']._serialized_start=435
  _globals['_SENSORREADING']._serialized_end=479
  _globals['_RCOUTDATAREQUEST']._serialized_start=481
  _globals['_RCOUTDATAREQUEST']._serialized_end=517
  _globals['_RCOUTDATARESPONSE']._serialized_start=519
  _globals['_RCOUTDATARESPONSE']._serialized_end=572
  _globals['_DRIVERSERVICE']._serialized_start=575
  _globals['_DRIVERSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
